# Generated by Django 5.1.1 on 2026-01-13 02:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this webhook event",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier for the webhook source (e.g., 'stripe', 'paypal')",
                        max_length=50,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="Unique event ID from the provider for idempotency",
                        max_length=255,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="The full JSON payload received from the webhook"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="received",
                        help_text="Processing status of the webhook event",
                        max_length=20,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when webhook was received",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when processing completed",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Details of the error if processing failed",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times processing has been attempted",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "event_id"],
                        name="webhooks_we_provide_8c9272_idx",
                    ),
                    models.Index(
                        fields=["status", "received_at"],
                        name="webhooks_we_status_4d802a_idx",
                    ),
                ],
                "unique_together": {("provider", "event_id")},
            },
        ),
    ]
