# Generated by Django 5.1.1 on 2026-01-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaintenanceMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Enable maintenance mode site-wide"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        default="We're currently making important updates to our site. Please check back soon!",
                        help_text="Message to display during maintenance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Maintenance Mode",
                "verbose_name_plural": "Maintenance Mode",
            },
        ),
    ]
